### PR TITLE
'Original' Charge Class update (follow on from PR #410)

### PR DESCRIPTION
**Pull request by ahullah**
Fix to include @marc-perreaut and TF1 feedback

### CODE REVIEW

**Review by SonalGarg-SG — APPROVED** [review]

**Review by kotzenjh — APPROVED** [review]

**Comment by ahullah** [comment]
Need to add a clarification to indicate that Corrections are only applicable to previous billing periods i.e. for stuff that has already been invoiced .... corrections that are happening in month for charges that are not yet invoiced are classified as Original

**Comment by udam-f2** [comment]
Group had an issue with 'Original' for providers that do delta updates within the billing period. However, the group did agree that the current wording for Standard and Correction aren't sufficient as they need to describe 'correction' as applying to a previous release. Decision was to revisit this during consistency review.

**Comment by AWS-ZachErdman** [comment]
> Member group raised the issue with 'Original' for providers that do delta updates within the billing period. However, the group did agree that the current wording for Standard and Correction aren't sufficient as they need to describe 'correction' as applying to a previous release. Decision was to revisit this during consistency review.

AWS does updates within a billing period, as well, but as long as "Correction" is only used for line items that are being corrected from previous billing periods, this is not an issue.

If Im in a discussion and I need to refer to a previous charge that a correction line applies applies to, Im going to refer to the “Original charge”, not the "Standard charge".

"Standard charge" in conversations could more easily be confused with what standard is referring to (e.g., standard pricing)

**Comment by AWS-ZachErdman** [comment]
> Member group raised the issue with 'Original' for providers that do delta updates within the billing period. However, the group did agree that the current wording for Standard and Correction aren't sufficient as they need to describe 'correction' as applying to a previous release. Decision was to revisit this during consistency review.

@udam-f2 AWS does updates to line items within a billing period, as well, but as long as "Correction" is only used for line items that are being corrected from previous billing periods, this is not an issue. We would only issue "Correction" on line items that were changing something in a previous billing period.

If Im in a discussion and I need to refer to a previous charge that a correction line applies applies to, Im going to refer to the “Original charge”, not the "Standard charge".

"Standard charge" in conversations could more easily be confused with what standard is referring to (e.g., standard pricing)

**Comment by jpradocueva** [comment]
The group agreed to move this PR to release v1.1 during the Members' meeting on April 25.

**Comment by marc-perreaut** [comment]
> The group agreed to move this PR to release v1.1 during the Members' meeting on April 25.

Is the change of an allowed value backward-compatible?
Wouldn't that change break anything checking ChargeClass=Standard?
Practitioners may adapt from v1.0 to v1.1 by checking ChargeClass=Standard or Original, but that implies a change in data processing.

**Comment by jpradocueva** [comment]
TF1&2 agreed to close the PR on Friday April 26.

**Comment by ijurica** [comment]
follow-up on https://github.com/FinOps-Open-Cost-and-Usage-Spec/FOCUS_Spec/pull/422#issuecomment-2078328250

In cases where a Provider does not deliver snapshots of data but instead provides an original charge record followed by subsequent increments and decrements within the same billing period, we should expect multiple (FOCUS) ChargeClass: non-correction records. 

The first record would represent the actual original charge (*1st row in the Table below*), followed by one or more subsequent charge records indicating corrections (or adjustments) provided within the same billing period as the original (*2nd row in the Table below*).  

In such cases, having multiple (FOCUS) ChargeClass: "Original" records would be confusing.

**ALTERNATIVES:**

- OPTION A: Regular / Correction (initial version)
- OPTION B: Standard / Correction (currently in the working_draft)
- OPTION C: Original / Correction (this PR)
- OPTION D: Original / Subsequent / Correction (something to consider)
- Etc.



| #   | Descripion                           | x_CorrectionFlag | ChargeClass (option A) | ChargeClass (option B) | ChargeClass (option C) | ChargeClass (option D) | BillingPeriodStart     | BillingPeriodEnd       | ChargePeriodStart     | ChargePeriodEnd       | ChargeCategory | SkuId    | SkuPriceId    | PricingQuantity | BilledCost |
|-----|--------------------------------------|------------------|------------------------|------------------------|------------------------|------------------------|------------------------|------------------------|------------------------|------------------------|----------------|----------|---------------|-----------------|------------|
| 1   | Original                             | FALSE            | Regular                | Standard               | Original               | Original               | 2023-08-01T00:00:00Z  | 2023-09-01T00:00:00Z  | 2023-08-03T00:00:00Z  | 2023-08-04T00:00:00Z  | Usage            | SKU-ID-1 | SKU-PRICE-ID-1 | 10.00           | 100.00     |
| 2   | Subsequent; FOCUS: non-correction    | TRUE             | Regular                | Standard               | Original               | Subsequent?            | 2023-08-01T00:00:00Z  | 2023-09-01T00:00:00Z  | 2023-08-03T00:00:00Z  | 2023-08-04T00:00:00Z  | Usage            | SKU-ID-1 | SKU-PRICE-ID-1 | 1.00            | 10.00      |
| 3   | Subsequent; FOCUS: correction        | TRUE             | Correction             | Correction             | Correction             | Correction             | 2023-09-01T00:00:00Z  | 2023-10-01T00:00:00Z  | 2023-08-03T00:00:00Z  | 2023-08-04T00:00:00Z  | Usage            | SKU-ID-1 | SKU-PRICE-ID-1 | 2.00            | 20.00      |

**Comment by AWS-ZachErdman** [comment]
Thanks for sharing this analysis @ijurica. 

I can understand the hesitation with "Original" when you have in-bill updates happening. However, extending that same logic makes me question whether line item #2 should be a correction. 

In my opinion, it makes sense for each of these subsequent charges to have a label "Original" since they are appearing in the billing period for which the charges actually originated.

Probably more important than the label itself is making our definitions clear that this column differentiates between what happens to a current billing period vs. a past billing period.

**Pull request closed without merging**
