### PR TITLE
service-category-dimension update

### PR DESCRIPTION
**Pull request by rodneyjoyce**
All other Dimensions use this standard (checked all 0.5 and 1.0)

### CODE REVIEW

**Review by flanakin — APPROVED** [review]
This is interesting. This format doesn't lend well to the goal of "user friendly" strings. Signing off for consistency, but I'd argue we should probably go the other way 😜

@udam-f2, curious about your thoughts.

**Comment by rodneyjoyce** [comment]
> This is interesting. This format doesn't lend well to the goal of "user friendly" strings. Signing off for consistency, but I'd argue we should probably go the other way 😜
> 
> @udam-f2, curious about your thoughts.



> This is interesting. This format doesn't lend well to the goal of "user friendly" strings. Signing off for consistency, but I'd argue we should probably go the other way 😜
> 
> @udam-f2, curious about your thoughts.

@udam-f2  suggested this change - at least now 0.5 and 1.0 Dimensions are all the same. I personally prefer the user-friendly/English version.

**Comment by flanakin** [comment]
Let's get it consistent first and then we can handle the broad change separately, if we want.

**Comment by udam-f2** [comment]
> Let's get it consistent first and then we can handle the broad change separately, if we want.

Yep, When I said it, I added it to my list of on-going spec-wide changes that we need to discuss and make to make more consistent. If you find any, let me know and I can add to my list. This one is #10 on the list :D

**Review by udam-f2 — APPROVED** [review]

**Pull request merged**
