### PR TITLE
FOCUS #330: Update chargeclass value from "Regular" to "Standard"

### PR DESCRIPTION
**Pull request by thecloudman**
Pricing category had the value "on-demand" changed to "Standard", so recommend keeping consistency in naming and have charge class value as "Standard" instead of "Regular"

### CODE REVIEW

**Comment by ahullah** [comment]
I don't have an objection here... makes sense to improve consistency

**Review by ahullah — APPROVED** [review]

**Review by flanakin — APPROVED** [review]
I feel like there's a more intentional word, but this is an improvement to "Regular". That always felt like a placeholder until we found something more appropriate.

**Review by mike-finopsorg — APPROVED** [review]

**Comment by udam-f2** [comment]
I believe @marc-perreaut was going to suggest 'Original' for which there was a good amount of support. His logic was it suggests this is the original charge as opposed to the 'correction' that comes after the fact. He mentioned this was already added as a comment in the PR but I'm not sure I see it - adding as a comment to not lose the suggestion. 

FYI @mike-finopsorg @flanakin @ahullah

**Comment by marc-perreaut** [comment]
> This morning in TF1 @marc-perreaut suggested 'Original' for which there was a good amount of support. His logic was it suggests this is the original charge as opposed to the 'correction' that comes after the fact. He mentioned this was already added as a comment in the PR but I'm not sure I see it - adding as a comment to not lose the suggestion.
> 
> FYI @mike-finopsorg @flanakin @ahullah

Sorry, I actually commented in other PR #412
https://github.com/FinOps-Open-Cost-and-Usage-Spec/FOCUS_Spec/pull/412/files#r1576446160

Also maybe a suggestion for a more explicit name for ChargeClass could be ChargeOccurrence.
Indeed, a charge occurrence may be either the original occurrence or a correction occurrence.

**Comment by ahullah** [comment]
Ok I'm just trying to reconcile that with the proposed 'percent' category we were thinking of adding to charge class to accommodate services that are not charged on a unit rate..... Actually thinking about this should original/regular actually be 'unit' as we are normality accounting for services consumed in units....???

**Comment by ahullah** [comment]
Apologies I merged this too soon will submit a separate PR to incorporate @marc-perreaut comment and the TF1 discussion to move this column to Original

**Comment by ahullah** [comment]
follow on update to 'Original' now in PR #422

**Pull request merged**
