### PR TITLE
[EDITORIAL - Alternate version] Mark commitment discount purchase's pricing_category as "Standard"

### PR DESCRIPTION
**Pull request by cnharris10**

### CODE REVIEW

**Review by ijurica — APPROVED** [review]

**Comment by ijurica** [comment]
How should we categorize Unused Usage records—as Standard or Committed? 
If purchases of commitment discounts are categorized as Standard, the unused portions of those purchases should also be categorized as Standard, right?

**Comment by cnharris10** [comment]
> How should we categorize Unused Usage records—as Standard or Committed? If purchases of commitment discounts are categorized as Standard, the unused portions of those purchases should also be categorized as Standard? It is covered by commitment discount purchase (i.e., BilledCost is 0), but is it Standard or Committed?
> 
> > **PricingCategory values** (for reference)
> > 
> > * **Standard:** Charges priced at the agreed upon rate for the billing account, including negotiated discounts. This includes any flat rate and volume/tiered pricing but does not include dynamic or commitment discount pricing.
> > * **Dynamic:** ...
> > * **Committed:** Charges with reduced prices due to a commitment discount specified by the Commitment Discount ID.
> > * **Other:** ...

Definitely `Committed`.  You're just amortizing what was pre-purchased, non-refundable (after any initial return period), and thus is committed.

**Comment by jpradocueva** [comment]
### Action Items from TF-2 call on October 2nd:
- [ ] [TF2-[#579](https://github.com/FinOps-Open-Cost-and-Usage-Spec/FOCUS_Spec/issues/579) ] Chris, @cnharris10 : Create a separate PR to update relevant documentation and clarify definitions.

**Review by udam-f2 — APPROVED** [review]

**Comment by jpradocueva** [comment]
Approved during the Members' call on October 3.

**Review by AWS-ZachErdman — APPROVED** [review]

**Pull request merged**
