### PR TITLE
Updated versioning/id approach to metadata

### PR DESCRIPTION
**Pull request by mike-finopsorg**
Removed DataGeneratorVersion
Added SchemaId under schema section
Moved ProviderTagPrefixes to live under the column definition of the Schema

### CODE REVIEW

**Comment by rileyjenk** [comment]
@mike-finopsorg I updated the supporting content to match this.

**Review by rileyjenk — APPROVED** [review]

**Review by ahullah — APPROVED** [review]

**Comment by udam-f2** [comment]
Member group approved the changes on 4/25.

**Review by SonalGarg-SG — APPROVED** [review]

**Review by kotzenjh — APPROVED** [review]
The change makes sense to move to a uniform way to also display provider tags

**Comment by jpradocueva** [comment]
@udam-f2, @mike-finopsorg could one of you please approve this PR? The PR was agreed upon by the group at the Members' meeting on April 25.

**Review by udam-f2 — APPROVED** [review]

**Pull request merged**
